name: 53Lunches
favicon: null
layout_spectrum: 0.24548
typography_spectrum: 0.8544161063618958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3edea'
    - '#b1cfd3'
    - '#93afa6'
    - '#292716'
    - '#6a5d36'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
